const fs = require('fs');
const path = require('path');

// The Centralized Locator Repository's runtime cache — regenerated by the
// backend (locatorRepository.service.js) every time a locator is healed on
// ANY execution path. This file is what makes terminal execution, the
// dashboard, Jira-triggered runs, and the scheduler all resolve
// identically — they all read this exact file, not an in-memory or
// per-process cache.
const RESOLVED_CACHE_PATH = path.join(__dirname, 'resolved-locators.json');

function loadJson(filePath) {
  try {
    return JSON.parse(fs.readFileSync(filePath, 'utf-8'));
  } catch {
    return {};
  }
}

/**
 * Resolves the selector a Page Object should use for `key` ("ClassName.property").
 * Resolution order:
 *   1. Centralized Locator Repository cache (resolved-locators.json) — a
 *      real, live-verified fix the AI Healing Agent produced, on ANY
 *      execution path. Used regardless of Git-approval status — approval
 *      only gates whether the fix gets committed to source, not whether
 *      it's used at runtime (a rejected entry is removed from this cache).
 *   2. The hardcoded default the Page Object defines inline.
 */
function resolve(key, defaultLocator) {
  const resolved = loadJson(RESOLVED_CACHE_PATH);
  const entry = resolved[key];
  if (entry?.locator) {
    // Surfaces in the run's runtime logs (captured via the list reporter),
    // satisfying "never silently use a cached locator without indicating this".
    console.log(`[LocatorResolver] Healed locator found in repository for "${key}" — using previously validated locator (status: ${entry.status}, confidence: ${entry.confidence}%).`);
    return entry.locator;
  }

  return defaultLocator;
}

module.exports = { resolve, RESOLVED_CACHE_PATH };
