const base = require('@playwright/test');
const fs = require('fs');
const path = require('path');

// Generic, per-test failure capture — replaces hardcoded per-module
// "reproduce" navigation scripts entirely. Instead of guessing how to get
// back to a similar page after the fact, this captures the REAL DOM/URL at
// the exact moment the test actually failed, for every test, automatically.
// The AI Healing Agent reads this artifact directly (see
// backend/src/services/demoHealingAgent.service.js) instead of re-deriving
// app-specific navigation steps.
const CAPTURE_DIR = path.join(__dirname, '..', '..', 'test-results', 'failure-context');

// Regenerated by backend/src/services/timeoutRemediation.service.js the
// moment a bumped timeout is live-verified (a retry that actually passed) —
// read here so every subsequent run of the same test starts with the
// verified override already applied, instead of failing the same way again.
const TIMEOUT_CACHE_PATH = path.join(__dirname, 'resolved-timeouts.json');

function loadTimeoutCache() {
  try {
    return JSON.parse(fs.readFileSync(TIMEOUT_CACHE_PATH, 'utf-8'));
  } catch {
    return {};
  }
}

function captureKeyFor(testTitle) {
  return testTitle.replace(/[^a-zA-Z0-9]/g, '_').slice(0, 150);
}

const test = base.test.extend({
  page: async ({ page }, use, testInfo) => {
    // Applied before use(page) — i.e. before this test's own beforeEach
    // hooks run — since a bumped timeout also needs to cover a slow
    // beforeEach, not just the test body itself.
    const override = loadTimeoutCache()[testInfo.title];
    if (override) {
      console.log(`[TimeoutResolver] Using live-verified timeout override for "${testInfo.title}": ${override.bumpedTimeoutMs}ms (was ${override.originalTimeoutMs}ms)`);
      testInfo.setTimeout(override.bumpedTimeoutMs);
    }

    await use(page);
    if (testInfo.status === testInfo.expectedStatus) return; // test passed — nothing to capture

    try {
      const html = await page.content();
      const url = page.url();
      // Capturing the URL alone isn't enough for any authenticated page — a
      // fresh browser context has no session, so navigating straight there
      // just bounces back to the login page via the app's own client-side
      // auth guard. storageState() captures whatever localStorage/cookies
      // Playwright already tracks (session tokens etc.), generically, with
      // no per-app knowledge — the healing agent restores this into its own
      // context so it sees the exact same authenticated state the test did.
      const storageState = await page.context().storageState();
      fs.mkdirSync(CAPTURE_DIR, { recursive: true });
      fs.writeFileSync(
        path.join(CAPTURE_DIR, `${captureKeyFor(testInfo.title)}.json`),
        JSON.stringify({ html, url, storageState, title: testInfo.title, capturedAt: Date.now() })
      );
    } catch {
      // Best-effort — a capture failure must never mask the real test failure.
    }
  },
});

module.exports = { test, expect: base.expect, captureKeyFor, CAPTURE_DIR };
